name: Build & Deploy
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: NullVoxPopuli/action-setup-pnpm@v2.3.0
      with:
        no-lockfile: true

    - name: pnpm install, build
      run: |
        pnpm install
        pnpm run build

    - name: Deploy to another repository
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: git@github.com:Carina957/Carina957.github.io.git
        BRANCH: main
        FOLDER: docs/.vitepress/dist
        SSH_PRIVATE_KEY: ${{secrets.DEPLOY_PRIVATE_KEY}}
    # - name: Deploy
    #   uses: cpina/github-action-push-to-another-repository@main
    #   env:
    #     SSH_DEPLOY_KEY: ${ secrets.SSH_DEPLOY_KEY }1
    #   with:
    #     source-directory: 'docs/.vitepress/dist'
    #     destination-github-username: 'Carina957'
    #     destination-repository-name: 'Carina957.github.io'
    #     user-email: chis_x@foxmail.com
    #     target-branch: main
