name: Build and deploy.
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: NullVoxPopuli/action-setup-pnpm@v2
      with:
        node-registry-url: 'https://registry.npmjs.org'
        node-version: 18
        cache: 'pnpm'

    - name: pnpm install, build
      run: |
        pnpm install
        pnpm run build

    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: git@github.com:Carina957/Carina957.github.io.git
        BRANCH: main
        FOLDER: docs/.vitepress/dist
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}

